version: '3'

services:
  next-app:
    container_name: next-app
    build:
      context: ./next-app
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    ports:
      - ${PORT_WEB}:3000
